### ISSUE TITLE
Installation links

### ISSUE THREAD

**Issue by ghost** [nirm03/SublimeLinter-clang#1]
. . .

**Comment by nirm03** [comment]
The plugin tries to compile for C/C++ based on your syntax. Could you try the following:
1. Check your syntax (far lower right corner.) Maybe you're using C instead then C++?
1. Do the following: open the command palette (cmd-shift-p), and run "SublimeLinter: Enable Debug Mode"
   than bring up the python panel (control-`), and edit you cpp file to force a linter check.
   You should see the executed clang command. Can you post it here?

**Comment by nirm03** [comment]
The plugin actually recognized that you're working with C++ (hence, -x c++)
but for some reason, clang couldn't find the iostream header in your system.
Normally this should be implicitly set by the `-x c++` specification.

What OS (and exact version) are you using? My guess is that your libc++ is in a non-standard location.
Can you search your host for the iostream header and let me know where it's located?

You could easily work around this issue by explicitly adding the path to iostream as an include dir.
Something like that (change 4.7 to whatever version you're using):

```
{
    "linters": {
        "clang": {
            "include_dirs": [
                "/usr/include/c++/4.7/"
            ]
    }
}
```

But that's a nasty way to solve this. so it's better to really figure out what happened here.

**Comment by nirm03** [comment]
Funny. I'm using Linux Mint 14, and everything works well for me.
Ok. Try the following in the shell:

```
locate iostream
```

and post the output here.

**Comment by nirm03** [comment]
It lints cout and endl because iostream is not included...

Wow, you even use the same c++ version as me.
Can you try to add the following to the sublimelinter configuration and see if it solves the problem:

```
{
    "linters": {
        "clang": {
            "extra_flags": "-std=c++11 -stdlib=libstdc++"
        }
    }
}

```

Alternatively, you can decide not to learn C++ and start learning a nicer language instead ;)

**Comment by nirm03** [comment]
Ok, last resort. Modify your "include_dirs" line likewise:

```
"include_dirs": ["/usr/include/c++/4.7"]
```

and send me the output of the python console (control-`)

Also, can you send me the output of this shell command:

```
dpkg -l | grep libstd
```

**Comment by nirm03** [comment]
Can you compile with clang from the shell? What if you do:
`clang -x c++ your_file.cpp` ?

**Comment by nirm03** [comment]
Sorry, I meant:
`clang -cc1 -x c++ your_file.cpp`

**Comment by nirm03** [comment]
Ok. so clang doesn't work at all for you...Regardless of the linter.
How did you get clang installed on your system?

**Comment by nirm03** [comment]
Just for Voodoo's sake, how about: `clang++ main.cpp`

**Comment by nirm03** [comment]
Hmm. I'm not sure what the difference is. Ok. I'll investigate this when I get the chance, and maybe try to have it call clang++ anyway. In the meantime, can you try  each one of these in the shell and let me know if one of them works for you?
`clang -cc1 -xc++ -lc++ main.cpp`
`clang -cc1 -xc++ -lstdc++ main.cpp`

**Comment by nirm03** [comment]
How about: `clang -x c++ -lstdc++ main.cpp`

**Comment by nirm03** [comment]
and also, can you do:
`clang++ -v main.cpp`

That would be very helpful.

**Comment by nirm03** [comment]
Wow, your clang++ command line is quite crazy. It explicitly includes lots of libraries. No wonder this wasn't enough.
I've made a small modification to the linter that might work for you. can you try it out?.
Just replace the contents of `~/.config/sublime-text-3/Packages/SublimeLinter-clang/linter.py`
with the code below and let me know how it goes. 

```
#
# linter.py
# Linter for SublimeLinter3, a code checking framework for Sublime Text 3
#
# Written by nirm03
# Copyright (c) 2013 nirm03
#
# License: MIT
#

"""This module exports the Clang plugin class."""

from SublimeLinter.lint import Linter, util, persist


class Clang(Linter):

    """Provides an interface to clang."""

    syntax = ('c', 'c improved', 'c++')
    executable = 'clang'

    # We are missing out on some errors by ignoring multiline messages.
    regex = (
        r'^<stdin>:(?P<line>\d+):(?P<col>\d+): '
        r'(?:(?P<error>(error|fatal error))|(?P<warning>warning)): '
        r'(?P<message>.+)'
    )
    multiline = False

    line_col_base = (1, 1)
    error_stream = util.STREAM_BOTH
    selectors = {}
    word_re = None
    defaults = {
        'include_dirs': [],
        'extra_flags': ""
    }
    inline_settings = None
    inline_overrides = None
    comment_re = None

    base_args = ' -cc1 -fsyntax-only -fno-caret-diagnostics -Wall '

    def cmd(self):
        """
        Return the command line to execute.

        We override this method, so we can add extra flags and include paths
        based on the 'include_dirs' and 'extra_flags' settings.
        """
        result = self.executable_path
        if persist.get_syntax(self.view) == 'c++':
            result += '++'

        result += self.base_args

        settings = self.get_view_settings()
        result += settings.get('extra_flags')

        if persist.get_syntax(self.view) == 'c++':
            result += ' -x c++ -fcxx-exceptions'

        include_dirs = settings.get('include_dirs')
        if include_dirs:
            result += ' -I ' + ' -I '.join(settings.get('include_dirs'))

        return result

```

**Comment by nirm03** [comment]
No way :) Ok, can you post the python command palette output now?

**Comment by nirm03** [comment]
I'm sorry. I just don't know. I thought I gave your compiler everything it wants to work...
you could try playing around with all the options in the linter.py file.
For example, trying to remove '-x c++', or you can paste the entire clang command line from your 'clang++ -v' into the extra_flags variable.

If you find a solution, I'd be happy to hear, and maybe improve the plugin...

**Comment by nirm03** [comment]
If you're still experiencing this problem, let's try a few more command lines.
In the shell, can you try each one of these:
`clang++ -cc1 -fsyntax-only -fno-caret-diagnostics -Wall -fcxx-exceptions < main.cpp`
`clang++ -cc1 -fsyntax-only -fno-caret-diagnostics -Wall -x c++ -fcxx-exceptions < main.cpp`
And last but not least. this is a long one, so bear with me:
`clang++ -cc1 -fsyntax-only -fno-caret-diagnostics -Wall -x c++ -fcxx-exceptions -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/c++/4.7 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/c++/4.7/x86_64-linux-gnu -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/c++/4.7/backward -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/x86_64-linux-gnu/c++/4.7 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/x86_64-linux-gnu/c++/4.7/x86_64-linux-gnu -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/x86_64-linux-gnu/c++/4.7/backward -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/x86_64-linux-gnu/c++/4.7 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/x86_64-linux-gnu/c++/4.7/x86_64-linux-gnu -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/x86_64-linux-gnu/c++/4.7/backward -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/c++ -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/c++/x86_64-linux-gnu -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/c++/backward -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/clang/3.2/include -internal-isystem /usr/include/clang/3.2/include/ -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /usr/include < main.cpp`

**Comment by nirm03** [comment]
Ok, can you try to put the whole line below as the extra_flags variable in the linter configuration?
You can use the normal plugin and not the special linter.py file I gave you to try before.

`-internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/c++/4.7 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/c++/4.7/x86_64-linux-gnu -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/c++/4.7/backward -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/x86_64-linux-gnu/c++/4.7 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/x86_64-linux-gnu/c++/4.7/x86_64-linux-gnu -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/x86_64-linux-gnu/c++/4.7/backward -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/x86_64-linux-gnu/c++/4.7 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/x86_64-linux-gnu/c++/4.7/x86_64-linux-gnu -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/x86_64-linux-gnu/c++/4.7/backward -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/c++ -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/c++/x86_64-linux-gnu -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../../include/c++/backward -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/clang/3.2/include -internal-isystem /usr/include/clang/3.2/include/ -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /usr/include`

**Comment by nirm03** [comment]
Hehe, a beer won't be necessary. It will spoil all the fun. Besides, I have plenty of beer already ;)

I am however planning to make an improvement, based on your issue,
I might put out a test version that automatically grabs all these extra flags, so maybe,
if you don't mind, you can try it out before I release it?

**Comment by xsleonard** [comment]
The problem is the -cc1 flag.

http://clang.llvm.org/docs/FAQ.html#i-run-clang-cc1-and-get-weird-errors-about-missing-headers

**Comment by Manck** [comment]
Just as an update or comment, in newer versions of software it needs to be this text the one you have to paste at the extra flags line: 

 "-internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/x86_64-linux-gnu -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/backward -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8/x86_64-linux-gnu -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8/backward -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8/x86_64-linux-gnu -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8/backward -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++ -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/x86_64-linux-gnu -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/backward -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/clang/3.2/include -internal-isystem /usr/include/clang/3.4/include/ -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /usr/include"
