### ISSUE TITLE
get_project_folder breaks on unsaved files

### ISSUE THREAD

**Issue by Optiligence** [nirm03/SublimeLinter-clang#18]
Unsaved files have no filename which breaks linting.

**Comment by Reobos** [comment]
I saw this issue and made a fix to my linter contribution `avr-gcc` which is very closely based on (copied from) this one. 
In the `get_project_folder()` function, I added a check to see if the filename exists and returns `'.'` if none is found. The extra bit of code is:

    # Use current file's folder when no project file is opened.
    proj_file = sublime.active_window().active_view().file_name()
    if proj_file:
        return os.path.dirname(proj_file)
    return '.'

See the code here: [https://github.com/ChisholmKyle/SublimeLinter-contrib-avr-gcc/blob/master/linter.py#L27](https://github.com/ChisholmKyle/SublimeLinter-contrib-avr-gcc/blob/master/linter.py#L27).

**Comment by Optiligence** [comment]
Wanna create a pull request with that or you want me to do it?

**Comment by Reobos** [comment]
It's a little annoying to do a pull request and it's such a small change, please go for it!

I'm not sure if this should be a new topic, but adding language-specific flags (`extra_cflags` and `extra_cxxflags`) like EasyClangComplete is really a quick feature addition and doesn't have to break anything - see [SublimeLinter-contrib-avr-gcc](https://github.com/ChisholmKyle/SublimeLinter-contrib-avr-gcc/blob/master/linter.py#L94)
The extra C/C++ flags are really helpful for projects with mixed C and C++ source files. What do you think?

**Comment by Optiligence** [comment]
I’m not a maintainer here (this is just my issue) but I created the PR now. 
I was merely suggesting that you submit PRs if you are sure (and even if not^^) about some changes.

**Comment by ooJerryLeeoo** [comment]
So when to update a new release?
