### ISSUE TITLE
Sublime linter clang errors in #include directive but compilation does not complaint 

### ISSUE THREAD

**Issue by a-cellofan** [nirm03/SublimeLinter-clang#19]
Hi,

I get some errors in the Linter plug that are not error, but warnings during compilation time. For example, in the console I get something like:

SublimeLinter: clang: Vertex2_Inode.hpp ['clang', '-fsyntax-only', '-fno-caret-diagnostics', '-Wall', '-x', 'c++', '-I', '/opt/local/include', '-I', '/usr/local/include', '-I', '/opt/local/include/boost', '-I', '/opt/local/include/eigen3', '-'] 
SublimeLinter: clang output:
In file included from <stdin>:5:
In file included from ./../config.hpp:17:
./../std.hpp:42:3: warning: "we are compiling with clang"    [-W#warnings]
In file included from <stdin>:5:
In file included from ./../config.hpp:37:
./../inc_boost.hpp:16:2: warning: "Debugging mode in Boost" [-W#warnings]
./../inc_boost.hpp:17:9: warning: '__EXCEPTIONS' macro redefined [-Wmacro-redefined]
<built-in>:22:9: note: previous definition is here
In file included from <stdin>:5:
In file included from ./../config.hpp:41:
./../inc_eigen.hpp:26:6: warning: "Debugging mode in Eigen" [-W#warnings] 

but for the pluging the warning in black is a error, since in the file I have something like:
![](https://cloud.githubusercontent.com/assets/796941/7934015/9db6bb3a-091b-11e5-8bd8-b8dd03caebad.png)

I know that -Wall flag means: treat all the warnings as errors, but I do not know how to change the behavior in the plugging in order to change this errors with the plugging in simple warnings.

By the way. I update the MAC OS compiler in Yosemite to the new version: 

Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

that's the exact moment that I start having this problems. Before this update no problem at all.
My SublimeLinter.sublime-settings for the linter clang is:

"clang": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "extra_flags": "",
                "include_dirs": [
                    "/opt/local/include",
                    "/usr/local/include",
                    "/opt/local/include/boost",
                    "/opt/local/include/eigen3"
                ]
            },

I mean, not -Wall option at all.

Thanks in advance. 

Arturo.

**Comment by Optiligence** [comment]
The flag you think of is `-Werror` not `-Wall` and it doesn’t apply here (as you can see, there are no errors in the output). 
The regex indeed doesn’t indentify warnings with a backtrace correctly, I will propose a fix. 
In the end it’s just a cosmetic issue (there is still a problem originating from this line, it’s just the wrong color).

**Comment by a-cellofan** [comment]
Hi,

I have changed the regexp according to the link above and it is working.

Thank you very much.
