### ISSUE TITLE
[Enhancement] different args for C code and C++ code

### ISSUE THREAD

**Issue by equal-l2** [nirm03/SublimeLinter-clang#21]
When I want to lint C++1y code, I set args (in SublimeLinter Setting) like this:

``` json
"args": ["-Wall", "-std=c++1y"]
```

With this args, C code cannot be linted with error like this:
`
error: invalid argument '-std=c++1y' not allowed with 'C/ObjC'
`

A simple solution is to change args manually according to code type.

But I'd be happy if there are options like this:

``` json
"args_c": ["-Wall", "-std=c11"] // for C code
"args_cpp": ["-Wall", "-std=c++1y"] // for C++ code
```

**Comment by dralley** [comment]
Hi @equal-l2,

I don't have any objection to this, however the last time this was brought up @nirm03 suggested simply using a .sublimelinterrc file instead.  Would this work for your case?

Discussion in Issue #8, PR #10
