### ISSUE TITLE
Installation steps not clear

### ISSUE THREAD

**Issue by anat0lius** [nirm03/SublimeLinter-clang#31]
I'm on Linux, already installed `clang version 3.8.0-2ubuntu4` and it's on path.

I'm using the control package, I searched for sublimelinter and it only appears me `SublimeLinter-contrib-clang`, I guess is that the plugin and not `SublimeLinter-clang` as suggested on the Readme.  The installation seems to be correct, no errors. 

- I open a C++ project, try to do autocomplete, nothing happens. 
- I neither see any setting menu on sublime. I'm lost here, where do I find the settings? Do I need to write them?

**Comment by Optiligence** [comment]
This plugin only display warnings and errors, and offers no autocomplete functionality.

**Comment by anat0lius** [comment]
Ah ok, didn't know. 

I make typos and don't see any error message. 

I search for `toggle` with `ctr+shift+p` and I don't see any SublimeLinter entry

**Comment by Optiligence** [comment]
You can `Show Console` from the `View ` and enable `SublimeLinter Debug Mode` via the command palette to check for errors.

**Comment by anat0lius** [comment]
```
>>> SublimeLinter Debug Mode
  File "<string>", line 1
    SublimeLinter Debug Mode
                      ^
SyntaxError: invalid syntax
```
:s

**Comment by Optiligence** [comment]
the command palette (ctrl+shift+p) is different from the console

**Comment by anat0lius** [comment]
Sry. 

As I said before, if I search SublimeLinter on the command palette, there are no entries. I try `SublimeLinter Debug Mode` and nothing happens. 

So I guess the installation isn't complete?

**Comment by Optiligence** [comment]
Then i seems you didn’t install `SublimeLinter`.

**Comment by anat0lius** [comment]
```
SublimeLinter-contrib-clang/
├── LICENSE
├── linter.py
├── messages
│   └── install.txt
├── messages.json
├── package-metadata.json
└── README.md

1 directory, 6 files
```

These are the files installed. There is also the hidden file `.no-sublime-package`.

**Comment by Optiligence** [comment]
> This linter plugin for SublimeLinter

> SublimeLinter 3 must be installed in order to use this plugin.

**Comment by anat0lius** [comment]
I wasn't aware that `SublimeLinter` and yours were different plugins
