### ISSUE TITLE
Can't ignore specific error

### ISSUE THREAD

**Issue by tomeaton17** [nirm03/SublimeLinter-clang#32]
I am getting an error that a file cannot be found when I try to include it. I know that this is a false positive, so I am trying to remove this error from being shown by using the ignore match in the settings. `"ignore_match": [
                    "fatal error: 'stm32f1xx.h' file not found"
],`
That is the error shown in the console when I turn on debugging, but it still doesn't suppress the error. Is this feature not supported with this linter?

**Comment by Optiligence** [comment]
i don’t know about this feature, but this error should prevent clang from linting the rest of the file anyway, so i see no point in suppressing it
if clang doesn’t find a file then you should assist in finding it
i wouldn’t consider this a false positive but a misconfiguration

**Comment by tomeaton17** [comment]
Yes once I include the directory the error goes, but I have more configuration errors to do with the `stm32f1xx.h` file. Thanks for the help

**Comment by Optiligence** [comment]
If this` ignore_match` is a SublimeLinter setting which just filters linting messages i see no reason why it shouln’t also work with this plugin.
